spring:
  datasource:
    username: sa
    password: ''
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: 'true'
      path: /h2
  jpa:
    generate-ddl: true